DROP TABLE DEPART_TO;
DROP TABLE ARRIVE_TO;
DROP TABLE OPERATE_;
DROP TABLE ASSIGNED_TO;
DROP TABLE BASED_AT;
DROP TABLE PARKED_AT;
DROP TABLE COMMAND_;
DROP TABLE WORKS_FOR;
DROP TABLE OWNS_;
DROP TABLE DESTINATION;

DROP TABLE PILOT;
DROP TABLE AIRCRAFT;
DROP TABLE ROUTE_;
DROP TABLE AIRLINE;
DROP VIEW PILOTCOMMANDS_;